class Item {
    static catalog = {
        baton1: new Item("Bâton de marche", "baton1", "equipement", "arme", {strength: 0, intelligence: 2}),
        baton2: new Item("Branche de chêne", "baton2", "equipement", "arme", {strength: 0, intelligence: 4}),
        baton3: new Item("Bâton d'argent", "baton3", "equipement", "arme", {strength: 0, intelligence: 6}),
        baton4: new Item("Bâton de mage", "baton4", "equipement", "arme", {strength: 0, intelligence: 8}),
        baton5: new Item("Branche runique", "baton5", "equipement", "arme", {strength: 0, intelligence: 10}),
        baton6: new Item("Branche druidique", "baton6", "equipement", "arme", {strength: 0, intelligence: 12}),
        baton7: new Item("Bâton de cristal", "baton7", "equipement", "arme", {strength: 0, intelligence: 14}),
        baton8: new Item("Bâton d'obsidienne", "baton8", "equipement", "arme", {strength: 0, intelligence: 16}),
        baton9: new Item("Branche d'arbre-monde", "baton9", "equipement", "arme", {strength: 0, intelligence: 18}),
        baton10: new Item("Branche céleste", "baton10", "equipement", "arme", {strength: 0, intelligence: 20}),
        baton11: new Item("Bâton de la création", "baton11", "equipement", "arme", {strength: 0, intelligence: 22}),

        hache1: new Item("Hache émoussée", "hache1", "equipement", "arme", {strength: 2, intelligence: 0}),
        hache2: new Item("Hache de bûcheron", "hache2", "equipement", "arme", {strength: 4, intelligence: 0}),
        hache3: new Item("Marteau de forgeron", "hache3", "equipement", "arme", {strength: 6, intelligence: 0}),
        hache4: new Item("Marteau nain", "hache4", "equipement", "arme", {strength: 8, intelligence: 0}),
        hache5: new Item("Hache runique", "hache5", "equipement", "arme", {strength: 10, intelligence: 0}),
        hache6: new Item("Hache de berserker", "hache6", "equipement", "arme", {strength: 12, intelligence: 0}),
        hache7: new Item("Hache draconique", "hache7", "equipement", "arme", {strength: 14, intelligence: 0}),
        hache8: new Item("Marteau du chaos", "hache8", "equipement", "arme", {strength: 16, intelligence: 0}),
        hache9: new Item("Marteau de titan", "hache9", "equipement", "arme", {strength: 18, intelligence: 0}),
        hache10: new Item("Marteau de la forge céleste", "hache10", "equipement", "arme", {strength: 20, intelligence: 0}),
        hache11: new Item("Hache infernale", "hache11", "equipement", "arme", {strength: 22, intelligence: 0}),
    
        sword1: new Item("Épée rouillée", "sword1", "equipement", "arme", {strength: 1, intelligence: 1}),
        sword2: new Item("Épée d'entraînement", "sword2", "equipement", "arme", {strength: 2, intelligence: 2}),
        sword3: new Item("Lame de chevalier", "sword3", "equipement", "arme", {strength: 3, intelligence: 3}),
        sword4: new Item("Épée d'acier", "sword4", "equipement", "arme", {strength: 4, intelligence: 4}),
        sword5: new Item("Lame runique", "sword5", "equipement", "arme", {strength: 5, intelligence: 5}),
        sword6: new Item("Lame elfique", "sword6", "equipement", "arme", {strength: 6, intelligence: 6}),
        sword7: new Item("Épée du héros", "sword7", "equipement", "arme", {strength: 7, intelligence: 7}),
        sword8: new Item("Lame du seigneur", "sword8", "equipement", "arme", {strength: 8, intelligence: 8}),
        sword9: new Item("Épée du jugement", "sword9", "equipement", "arme", {strength: 9, intelligence: 9}),
        sword10: new Item("Lame céleste", "sword10", "equipement", "arme", {strength: 10, intelligence: 10}),
        sword11: new Item("Épée tranche-mondes", "sword11", "equipement", "arme", {strength: 11, intelligence: 11}),

        robe1: new Item("Robe de pèlerin", "robe1", "equipement", "armure", {agility: 0, vitality: 0, willpower: 2}),
        robe2: new Item("Robe en coton", "robe2", "equipement", "armure", {agility: 0, vitality: 0, willpower: 4}),
        robe3: new Item("Robe en lin", "robe3", "equipement", "armure", {agility: 0, vitality: 0, willpower: 6}),
        robe4: new Item("Robe en satin", "robe4", "equipement", "armure", {agility: 0, vitality: 0, willpower: 8}),
        robe5: new Item("Robe en velours", "robe5", "equipement", "armure", {agility: 0, vitality: 0, willpower: 10}),
        robe6: new Item("Robe en soie", "robe6", "equipement", "armure", {agility: 0, vitality: 0, willpower: 12}),
        robe7: new Item("Robe en duvet d'hippogriffe", "robe7", "equipement", "armure", {agility: 0, vitality: 0, willpower: 14}),
        robe8: new Item("Robe en satin céleste", "robe8", "equipement", "armure", {agility: 0, vitality: 0, willpower: 16}),
        robe9: new Item("Robe en soie elfique", "robe9", "equipement", "armure", {agility: 0, vitality: 0, willpower: 18}),
        robe10: new Item("Robe du sphinx", "robe10", "equipement", "armure", {agility: 0, vitality: 0, willpower: 20}),
        robe11: new Item("Robe astrale", "robe11", "equipement", "armure", {agility: 0, vitality: 0, willpower: 22}),
    
        lightArmor1: new Item("Pourpoint abîmé", "lightArmor1", "equipement", "armure", {agility: 2, vitality: 0, willpower: 0}),
        lightArmor2: new Item("Pourpoint renforcé", "lightArmor2", "equipement", "armure", {agility: 4, vitality: 0, willpower: 0}),
        lightArmor3: new Item("Pourpoint en cuir", "lightArmor3", "equipement", "armure", {agility: 6, vitality: 0, willpower: 0}),
        lightArmor4: new Item("Pourpoint couenne-solide", "lightArmor4", "equipement", "armure", {agility: 8, vitality: 0, willpower: 0}),
        lightArmor5: new Item("Pourpoint sylvestre", "lightArmor5", "equipement", "armure", {agility: 10, vitality: 0, willpower: 0}),
        lightArmor6: new Item("Pourpoint cuir de troll", "lightArmor6", "equipement", "armure", {agility: 12, vitality: 0, willpower: 0}),
        lightArmor7: new Item("Pourpoint de la wyverne", "lightArmor7", "equipement", "armure", {agility: 14, vitality: 0, willpower: 0}),
        lightArmor8: new Item("Pourpoint du zéphyr", "lightArmor8", "equipement", "armure", {agility: 16, vitality: 0, willpower: 0}),
        lightArmor9: new Item("Pourpoint draconique", "lightArmor9", "equipement", "armure", {agility: 18, vitality: 0, willpower: 0}),
        lightArmor10: new Item("Pourpoint du traqueur de démons", "lightArmor10", "equipement", "armure", {agility: 20, vitality: 0, willpower: 0}),
        lightArmor11: new Item("Pourpoint de l'invisible", "lightArmor11", "equipement", "armure", {agility: 22, vitality: 0, willpower: 0}),

        mediumArmor1: new Item("Armure usée", "mediumArmor1", "equipement", "armure", {agility: 1, vitality: 1, willpower: 0}),
        mediumArmor2: new Item("Armure souple", "mediumArmor2", "equipement", "armure", {agility: 2, vitality: 2, willpower: 0}),
        mediumArmor3: new Item("Armure en mailles d'acier", "mediumArmor3", "equipement", "armure", {agility: 3, vitality: 3, willpower: 0}),
        mediumArmor4: new Item("Armure tressée solide", "mediumArmor4", "equipement", "armure", {agility: 4, vitality: 4, willpower: 0}),
        mediumArmor5: new Item("Armure de racines", "mediumArmor5", "equipement", "armure", {agility: 5, vitality: 5, willpower: 0}),
        mediumArmor6: new Item("Armure antique", "mediumArmor6", "equipement", "armure", {agility: 6, vitality: 6, willpower: 0}),
        mediumArmor7: new Item("Armure d'écailles de dragonnet", "mediumArmor7", "equipement", "armure", {agility: 7, vitality: 7, willpower: 0}),
        mediumArmor8: new Item("Armure en mithril", "mediumArmor8", "equipement", "armure", {agility: 8, vitality: 8, willpower: 0}),
        mediumArmor9: new Item("Armure des ombres", "mediumArmor9", "equipement", "armure", {agility: 9, vitality: 9, willpower: 0}),
        mediumArmor10: new Item("Armure carapace de démon", "mediumArmor10", "equipement", "armure", {agility: 10, vitality: 10, willpower: 0}),
        mediumArmor11: new Item("Armure angélique", "mediumArmor11", "equipement", "armure", {agility: 11, vitality: 11, willpower: 0}),
    
        heavyArmor1: new Item("Cuirasse cabossée", "heavyArmor1", "equipement", "armure", {agility: 0, vitality: 2, willpower: 0}),
        heavyArmor2: new Item("Cuirasse de fer", "heavyArmor2", "equipement", "armure", {agility: 0, vitality: 4, willpower: 0}),
        heavyArmor3: new Item("Cuirasse en acier", "heavyArmor3", "equipement", "armure", {agility: 0, vitality: 6, willpower: 0}),
        heavyArmor4: new Item("Cuirasse à plaques", "heavyArmor4", "equipement", "armure", {agility: 0, vitality: 8, willpower: 0}),
        heavyArmor5: new Item("Cuirasse solide", "heavyArmor5", "equipement", "armure", {agility: 0, vitality: 10, willpower: 0}),
        heavyArmor6: new Item("Cuirasse de nain", "heavyArmor6", "equipement", "armure", {agility: 0, vitality: 12, willpower: 0}),
        heavyArmor7: new Item("Cuirasse en titane", "heavyArmor7", "equipement", "armure", {agility: 0, vitality: 14, willpower: 0}),
        heavyArmor8: new Item("Cuirasse en os de dragon", "heavyArmor8", "equipement", "armure", {agility: 0, vitality: 16, willpower: 0}),
        heavyArmor9: new Item("Cuirasse en adamantium", "heavyArmor9", "equipement", "armure", {agility: 0, vitality: 18, willpower: 0}),
        heavyArmor10: new Item("Cuirasse de roi", "heavyArmor10", "equipement", "armure", {agility: 0, vitality: 20, willpower: 0}),
        heavyArmor11: new Item("Cuirasse forgée des dieux", "heavyArmor11", "equipement", "armure", {agility: 0, vitality: 22, willpower: 0}),

        magicArmor1: new Item("Tunique rapiécée", "magicArmor1", "equipement", "armure", {agility: 0, vitality: 1, willpower: 1}),
        magicArmor2: new Item("Tunique simple", "magicArmor2", "equipement", "armure", {agility: 0, vitality: 2, willpower: 2}),
        magicArmor3: new Item("Tunique en fils d'araignée", "magicArmor3", "equipement", "armure", {agility: 0, vitality: 3, willpower: 3}),
        magicArmor4: new Item("Tunique d'arcaniste", "magicArmor4", "equipement", "armure", {agility: 0, vitality: 4, willpower: 4}),
        magicArmor5: new Item("Tunique runique", "magicArmor5", "equipement", "armure", {agility: 0, vitality: 5, willpower: 5}),
        magicArmor6: new Item("Tunique bénie", "magicArmor6", "equipement", "armure", {agility: 0, vitality: 6, willpower: 6}),
        magicArmor7: new Item("Tunique chimérique", "magicArmor7", "equipement", "armure", {agility: 0, vitality: 7, willpower: 7}),
        magicArmor8: new Item("Tunique démoniaque", "magicArmor8", "equipement", "armure", {agility: 0, vitality: 8, willpower: 8}),
        magicArmor9: new Item("Tunique des sélénites", "magicArmor9", "equipement", "armure", {agility: 0, vitality: 9, willpower: 9}),
        magicArmor10: new Item("Tunique de la liche", "magicArmor10", "equipement", "armure", {agility: 0, vitality: 10, willpower: 10}),
        magicArmor11: new Item("Tunique de roi satyr", "magicArmor11", "equipement", "armure", {agility: 0, vitality: 11, willpower: 11}),

        battleRobe1: new Item("Veste d'ermite", "battleRobe1", "equipement", "armure", {agility: 1, vitality: 0, willpower: 1}),
        battleRobe2: new Item("Veste de mage", "battleRobe2", "equipement", "armure", {agility: 2, vitality: 0, willpower: 2}),
        battleRobe3: new Item("Veste en toile durcie", "battleRobe3", "equipement", "armure", {agility: 3, vitality: 0, willpower: 3}),
        battleRobe4: new Item("Veste de druide", "battleRobe4", "equipement", "armure", {agility: 4, vitality: 0, willpower: 4}),
        battleRobe5: new Item("Veste mange-ténèbres", "battleRobe5", "equipement", "armure", {agility: 5, vitality: 0, willpower: 5}),
        battleRobe6: new Item("Veste de mage de guerre", "battleRobe6", "equipement", "armure", {agility: 6, vitality: 0, willpower: 6}),
        battleRobe7: new Item("Veste en élémentium", "battleRobe7", "equipement", "armure", {agility: 7, vitality: 0, willpower: 7}),
        battleRobe8: new Item("Veste sylvebranche", "battleRobe8", "equipement", "armure", {agility: 8, vitality: 0, willpower: 8}),
        battleRobe9: new Item("Veste de manticore", "battleRobe9", "equipement", "armure", {agility: 9, vitality: 0, willpower: 9}),
        battleRobe10: new Item("Veste touchée par les anges", "battleRobe10", "equipement", "armure", {agility: 10, vitality: 0, willpower: 10}),
        battleRobe11: new Item("Veste d'archimage", "battleRobe11", "equipement", "armure", {agility: 11, vitality: 0, willpower: 11}),
    
        potion1: new Item("Potion 4XS", "potion1", "consommable", "heal", 20),
        potion2: new Item("Potion 3XS", "potion2", "consommable", "heal", 40),
        potion3: new Item("Potion XXS", "potion3", "consommable", "heal", 60),
        potion4: new Item("Potion XS", "potion4", "consommable", "heal", 80),
        potion5: new Item("Potion S", "potion5", "consommable", "heal", 100),
        potion6: new Item("Potion M", "potion6", "consommable", "heal", 120),
        potion7: new Item("Potion L", "potion7", "consommable", "heal", 140),
        potion8: new Item("Potion XL", "potion8", "consommable", "heal", 160),
        potion9: new Item("Potion XXL", "potion9", "consommable", "heal", 180),
        potion10: new Item("Potion 3XL", "potion10", "consommable", "heal", 200),
        potion11: new Item("Potion 4XL", "potion11", "consommable", "heal", 220),

        ether1: new Item("Éther 4XS", "ether1", "consommable", "regen", 20),
        ether2: new Item("Éther 3XS", "ether2", "consommable", "regen", 40),
        ether3: new Item("Éther XXS", "ether3", "consommable", "regen", 60),
        ether4: new Item("Éther XS", "ether4", "consommable", "regen", 80),
        ether5: new Item("Éther S", "ether5", "consommable", "regen", 100),
        ether6: new Item("Éther M", "ether6", "consommable", "regen", 120),
        ether7: new Item("Éther L", "ether7", "consommable", "regen", 140),
        ether8: new Item("Éther XL", "ether8", "consommable", "regen", 160),
        ether9: new Item("Éther XXL", "ether9", "consommable", "regen", 180),
        ether10: new Item("Éther 3XL", "ether10", "consommable", "regen", 200),
        ether11: new Item("Éther 4XL", "ether11", "consommable", "regen", 220),

        rez1 : new Item("Plume d'ange 3XS", "rez1", "consommable", "resurrect", 0.1),
        rez2 : new Item("Plume d'ange XXS", "rez2", "consommable", "resurrect", 0.2),
        rez3 : new Item("Plume d'ange XS", "rez3", "consommable", "resurrect", 0.3),
        rez4 : new Item("Plume d'ange S", "rez4", "consommable", "resurrect", 0.4),
        rez5 : new Item("Plume d'ange M", "rez5", "consommable", "resurrect", 0.5),
        rez6 : new Item("Plume d'ange L", "rez6", "consommable", "resurrect", 0.6),
        rez7 : new Item("Plume d'ange XL", "rez7", "consommable", "resurrect", 0.7),
        rez8 : new Item("Plume d'ange XXL", "rez8", "consommable", "resurrect", 0.8),
        rez9 : new Item("Plume d'ange 3XL", "rez9", "consommable", "resurrect", 0.9),
        rez10 : new Item("Plume d'ange 4XL", "rez10", "consommable", "resurrect", 1),
    };
    
    constructor(nom, id, type, effet, valeur) {
        this.nom = nom;
        this.id = id;
        this.type = type;
        this.effet = effet;
        this.valeur = valeur;
    }

    static getItem(id) {
        return this.catalog[id]
    }
};