class Item {
    static catalog = {
        baton1: new Item("Bâton de marche", "baton1", "equipement", "arme", {strength: 0, intelligence: 2}),
        baton2: new Item("Branche de chêne", "baton2", "equipement", "arme", {strength: 0, intelligence: 4}),
        baton3: new Item("Bâton runique", "baton3", "equipement", "arme", {strength: 0, intelligence: 8}),
        baton4: new Item("Sceptre d'argent", "baton4", "equipement", "arme", {strength: 0, intelligence: 16}),
        baton5: new Item("Bâton de cristal", "baton5", "equipement", "arme", {strength: 0, intelligence: 26}),
        baton6: new Item("Branche druidique", "baton6", "equipement", "arme", {strength: 0, intelligence: 38}),
        baton7: new Item("Bâton de mage", "baton7", "equipement", "arme", {strength: 0, intelligence: 52}),
        baton8: new Item("Sceptre d'obsidienne", "baton8", "equipement", "arme", {strength: 0, intelligence: 68}),
        baton9: new Item("Branche d'arbre-monde", "baton9", "equipement", "arme", {strength: 0, intelligence: 86}),
        baton10: new Item("Bâton céleste", "baton10", "equipement", "arme", {strength: 0, intelligence: 106}),
        baton11: new Item("Bâton de la création", "baton11", "equipement", "arme", {strength: 0, intelligence: 128}),

        hache1: new Item("Hache émoussée", "hache1", "equipement", "arme", {strength: 2, intelligence: 0}),
        hache2: new Item("Hache de bûcheron", "hache2", "equipement", "arme", {strength: 4, intelligence: 0}),
        hache3: new Item("Marteau de forgeron", "hache3", "equipement", "arme", {strength: 8, intelligence: 0}),
        hache4: new Item("Marteau nain", "hache4", "equipement", "arme", {strength: 16, intelligence: 0}),
        hache5: new Item("Hache runique", "hache5", "equipement", "arme", {strength: 26, intelligence: 0}),
        hache6: new Item("Hache de berserker", "hache6", "equipement", "arme", {strength: 38, intelligence: 0}),
        hache7: new Item("Hache draconique", "hache7", "equipement", "arme", {strength: 52, intelligence: 0}),
        hache8: new Item("Marteau du chaos", "hache8", "equipement", "arme", {strength: 68, intelligence: 0}),
        hache9: new Item("Massue du titan", "hache9", "equipement", "arme", {strength: 86, intelligence: 0}),
        hache10: new Item("Massue de la forge céleste", "hache10", "equipement", "arme", {strength: 106, intelligence: 0}),
        hache11: new Item("Hache de l'anéantissement", "hache11", "equipement", "arme", {strength: 128, intelligence: 0}),
    
        sword1: new Item("Épée rouillée", "sword1", "equipement", "arme", {strength: 1, intelligence: 1}),
        sword2: new Item("Épée d'entraînement", "sword2", "equipement", "arme", {strength: 2, intelligence: 2}),
        sword3: new Item("Lame de chevalier", "sword3", "equipement", "arme", {strength: 4, intelligence: 4}),
        sword4: new Item("Épée d'acier", "sword4", "equipement", "arme", {strength: 8, intelligence: 8}),
        sword5: new Item("Épée runique", "sword5", "equipement", "arme", {strength: 13, intelligence: 13}),
        sword6: new Item("Lame elfique", "sword6", "equipement", "arme", {strength: 19, intelligence: 19}),
        sword7: new Item("Lame du héros", "sword7", "equipement", "arme", {strength: 26, intelligence: 26}),
        sword8: new Item("Épée du seigneur", "sword8", "equipement", "arme", {strength: 34, intelligence: 34}),
        sword9: new Item("Lame du Jugement", "sword9", "equipement", "arme", {strength: 43, intelligence: 43}),
        sword10: new Item("Lame céleste", "sword10", "equipement", "arme", {strength: 53, intelligence: 53}),
        sword11: new Item("Épée tranche-mondes", "sword11", "equipement", "arme", {strength: 64, intelligence: 64}),

        robe1: new Item("Robe usée", "robe1", "equipement", "armure", {agility: 0, vitality: 0, willpower: 2}),
        robe2: new Item("Robe d'apprenti", "robe2", "equipement", "armure", {agility: 0, vitality: 0, willpower: 4}),
        robe3: new Item("Robe mystique", "robe3", "equipement", "armure", {agility: 0, vitality: 0, willpower: 8}),
        robe4: new Item("Robe des arcanes", "robe4", "equipement", "armure", {agility: 0, vitality: 0, willpower: 16}),
        robe5: new Item("Robe runique", "robe5", "equipement", "armure", {agility: 0, vitality: 0, willpower: 26}),
        robe6: new Item("Robe elfique", "robe6", "equipement", "armure", {agility: 0, vitality: 0, willpower: 38}),
        robe7: new Item("Robe de mage royal", "robe7", "equipement", "armure", {agility: 0, vitality: 0, willpower: 52}),
        robe8: new Item("Robe céleste", "robe8", "equipement", "armure", {agility: 0, vitality: 0, willpower: 68}),
        robe9: new Item("Robe de l'archimage", "robe9", "equipement", "armure", {agility: 0, vitality: 0, willpower: 86}),
        robe10: new Item("Robe astrale", "robe10", "equipement", "armure", {agility: 0, vitality: 0, willpower: 106}),
        robe11: new Item("Robe du Grand Savoir", "robe11", "equipement", "armure", {agility: 0, vitality: 0, willpower: 128}),
    
        lightArmor1: new Item("Veste abîmée", "lightArmor1", "equipement", "armure", {agility: 2, vitality: 0, willpower: 0}),
        lightArmor2: new Item("Veste renforcée", "lightArmor2", "equipement", "armure", {agility: 4, vitality: 0, willpower: 0}),
        lightArmor3: new Item("Cape du vent", "lightArmor3", "equipement", "armure", {agility: 8, vitality: 0, willpower: 0}),
        lightArmor4: new Item("Armure de rôdeur", "lightArmor4", "equipement", "armure", {agility: 16, vitality: 0, willpower: 0}),
        lightArmor5: new Item("Manteau d'ombre", "lightArmor5", "equipement", "armure", {agility: 26, vitality: 0, willpower: 0}),
        lightArmor6: new Item("Armure sylvestre", "lightArmor6", "equipement", "armure", {agility: 38, vitality: 0, willpower: 0}),
        lightArmor7: new Item("Cape elfique", "lightArmor7", "equipement", "armure", {agility: 52, vitality: 0, willpower: 0}),
        lightArmor8: new Item("Veste du zéphyr", "lightArmor8", "equipement", "armure", {agility: 68, vitality: 0, willpower: 0}),
        lightArmor9: new Item("Veste du traqueur", "lightArmor9", "equipement", "armure", {agility: 86, vitality: 0, willpower: 0}),
        lightArmor10: new Item("Cape de l'invisible", "lightArmor10", "equipement", "armure", {agility: 106, vitality: 0, willpower: 0}),
        lightArmor11: new Item("Manteau des étoiles", "lightArmor11", "equipement", "armure", {agility: 128, vitality: 0, willpower: 0}),

        mediumArmor1: new Item("Armure matelassée trouée", "mediumArmor1", "equipement", "armure", {agility: 1, vitality: 1, willpower: 0}),
        mediumArmor2: new Item("Brigandine", "mediumArmor2", "equipement", "armure", {agility: 2, vitality: 2, willpower: 0}),
        mediumArmor3: new Item("Cotte de mailles", "mediumArmor3", "equipement", "armure", {agility: 4, vitality: 4, willpower: 0}),
        mediumArmor4: new Item("Armure en cuir de troll", "mediumArmor4", "equipement", "armure", {agility: 8, vitality: 8, willpower: 0}),
        mediumArmor5: new Item("Haubert de vétéran", "mediumArmor5", "equipement", "armure", {agility: 13, vitality: 13, willpower: 0}),
        mediumArmor6: new Item("Cuirasse d'assaut", "mediumArmor6", "equipement", "armure", {agility: 19, vitality: 19, willpower: 0}),
        mediumArmor7: new Item("Cotte en mithil", "mediumArmor7", "equipement", "armure", {agility: 26, vitality: 26, willpower: 0}),
        mediumArmor8: new Item("Armure en cuir de dragon", "mediumArmor8", "equipement", "armure", {agility: 34, vitality: 34, willpower: 0}),
        mediumArmor9: new Item("Cuirasse de feuilles d'adamantium", "mediumArmor9", "equipement", "armure", {agility: 43, vitality: 43, willpower: 0}),
        mediumArmor10: new Item("Brigandine enchantée", "mediumArmor10", "equipement", "armure", {agility: 53, vitality: 53, willpower: 0}),
        mediumArmor11: new Item("Cotte angélique", "mediumArmor11", "equipement", "armure", {agility: 64, vitality: 64, willpower: 0}),
    
        heavyArmor1: new Item("Plastron cabossé", "heavyArmor1", "equipement", "armure", {agility: 0, vitality: 2, willpower: 0}),
        heavyArmor2: new Item("Cuirasse de soldat", "heavyArmor2", "equipement", "armure", {agility: 0, vitality: 4, willpower: 0}),
        heavyArmor3: new Item("Armure de fer", "heavyArmor3", "equipement", "armure", {agility: 0, vitality: 8, willpower: 0}),
        heavyArmor4: new Item("Cotte d'acier", "heavyArmor4", "equipement", "armure", {agility: 0, vitality: 16, willpower: 0}),
        heavyArmor5: new Item("Garde de paladin", "heavyArmor5", "equipement", "armure", {agility: 0, vitality: 26, willpower: 0}),
        heavyArmor6: new Item("Armure draconique", "heavyArmor6", "equipement", "armure", {agility: 0, vitality: 38, willpower: 0}),
        heavyArmor7: new Item("Cuirasse impériale", "heavyArmor7", "equipement", "armure", {agility: 0, vitality: 52, willpower: 0}),
        heavyArmor8: new Item("Plastron du colosse", "heavyArmor8", "equipement", "armure", {agility: 0, vitality: 68, willpower: 0}),
        heavyArmor9: new Item("Armure du titan", "heavyArmor9", "equipement", "armure", {agility: 0, vitality: 86, willpower: 0}),
        heavyArmor10: new Item("Garde runique", "heavyArmor10", "equipement", "armure", {agility: 0, vitality: 106, willpower: 0}),
        heavyArmor11: new Item("Plastron forgé des dieux", "heavyArmor11", "equipement", "armure", {agility: 0, vitality: 128, willpower: 0}),

        magicArmor1: new Item("Veste rapiécée", "magicArmor1", "equipement", "armure", {agility: 0, vitality: 1, willpower: 1}),
        magicArmor2: new Item("Pourpoint d'invocateur", "magicArmor2", "equipement", "armure", {agility: 0, vitality: 2, willpower: 2}),
        magicArmor3: new Item("Robe renforcée de sage", "magicArmor3", "equipement", "armure", {agility: 0, vitality: 4, willpower: 4}),
        magicArmor4: new Item("Cuirasse de mage", "magicArmor4", "equipement", "armure", {agility: 0, vitality: 8, willpower: 8}),
        magicArmor5: new Item("Tunique runique", "magicArmor5", "equipement", "armure", {agility: 0, vitality: 13, willpower: 13}),
        magicArmor6: new Item("Cuirasse arcanique", "magicArmor6", "equipement", "armure", {agility: 0, vitality: 19, willpower: 19}),
        magicArmor7: new Item("Pastron enchanté", "magicArmor7", "equipement", "armure", {agility: 0, vitality: 26, willpower: 26}),
        magicArmor8: new Item("Robe en fils de mitrhil", "magicArmor8", "equipement", "armure", {agility: 0, vitality: 34, willpower: 34}),
        magicArmor9: new Item("Cuirasse divine", "magicArmor9", "equipement", "armure", {agility: 0, vitality: 43, willpower: 43}),
        magicArmor10: new Item("Robe renforcée des arcanes", "magicArmor10", "equipement", "armure", {agility: 0, vitality: 53, willpower: 53}),
        magicArmor11: new Item("Plastron en élémentium", "magicArmor11", "equipement", "armure", {agility: 0, vitality: 64, willpower: 64}),

        battleRobe1: new Item("Haillons d'ermite", "battleRobe1", "equipement", "armure", {agility: 1, vitality: 0, willpower: 1}),
        battleRobe2: new Item("Tunique de mage", "battleRobe2", "equipement", "armure", {agility: 2, vitality: 0, willpower: 2}),
        battleRobe3: new Item("Robe de l'exilé", "battleRobe3", "equipement", "armure", {agility: 4, vitality: 0, willpower: 4}),
        battleRobe4: new Item("Tunique arcanique", "battleRobe4", "equipement", "armure", {agility: 4, vitality: 0, willpower: 4}),
        battleRobe5: new Item("Robe de mage de guerre", "battleRobe5", "equipement", "armure", {agility: 13, vitality: 0, willpower: 13}),
        battleRobe6: new Item("Tunique du Cercle", "battleRobe6", "equipement", "armure", {agility: 19, vitality: 0, willpower: 19}),
        battleRobe7: new Item("Tunique d'incantateur", "battleRobe7", "equipement", "armure", {agility: 26, vitality: 0, willpower: 26}),
        battleRobe8: new Item("Robe de tacticien", "battleRobe8", "equipement", "armure", {agility: 34, vitality: 0, willpower: 68}),
        battleRobe9: new Item("Tunique boréale", "battleRobe9", "equipement", "armure", {agility: 43, vitality: 0, willpower: 43}),
        battleRobe10: new Item("Robe d'archevêque", "battleRobe10", "equipement", "armure", {agility: 53, vitality: 0, willpower: 53}),
        battleRobe11: new Item("Tunique touchée par les anges", "battleRobe11", "equipement", "armure", {agility: 64, vitality: 0, willpower: 64}),
    
        potion1: new Item("Potion 4XS", "potion1", "consommable", "heal", 20),
        potion2: new Item("Potion 3XS", "potion2", "consommable", "heal", 40),
        potion3: new Item("Potion XXS", "potion3", "consommable", "heal", 80),
        potion4: new Item("Potion XS", "potion4", "consommable", "heal", 160),
        potion5: new Item("Potion S", "potion5", "consommable", "heal", 260),
        potion6: new Item("Potion M", "potion6", "consommable", "heal", 380),
        potion7: new Item("Potion L", "potion7", "consommable", "heal", 520),
        potion8: new Item("Potion XL", "potion8", "consommable", "heal", 680),
        potion9: new Item("Potion XXL", "potion9", "consommable", "heal", 860),
        potion10: new Item("Potion 3XL", "potion10", "consommable", "heal", 1060),
        potion11: new Item("Potion 4XL", "potion11", "consommable", "heal", 1280),

        ether1: new Item("Ether 4XS", "ether1", "consommable", "regen", 20),
        ether2: new Item("Ether 3XS", "ether2", "consommable", "regen", 40),
        ether3: new Item("Ether XXS", "ether3", "consommable", "regen", 80),
        ether4: new Item("Ether XS", "ether4", "consommable", "regen", 160),
        ether5: new Item("Ether S", "ether5", "consommable", "regen", 260),
        ether6: new Item("Ether M", "ether6", "consommable", "regen", 380),
        ether7: new Item("Ether L", "ether7", "consommable", "regen", 520),
        ether8: new Item("Ether XL", "ether8", "consommable", "regen", 680),
        ether9: new Item("Ether XXL", "ether9", "consommable", "regen", 860),
        ether10: new Item("Ether 3XL", "ether10", "consommable", "regen", 1060),
        ether11: new Item("Ether 4XL", "ether11", "consommable", "regen", 1280),

        rez1 : new Item("Plume d'ange", "rez1", "consommable", "resurrect", 0.1),
        rez2 : new Item("Plume d'ange", "rez2", "consommable", "resurrect", 0.2),
        rez3 : new Item("Plume d'ange", "rez3", "consommable", "resurrect", 0.3),
        rez4 : new Item("Plume d'ange", "rez4", "consommable", "resurrect", 0.4),
        rez5 : new Item("Plume d'ange", "rez5", "consommable", "resurrect", 0.5),
        rez6 : new Item("Plume d'ange", "rez6", "consommable", "resurrect", 0.6),
        rez7 : new Item("Plume d'ange", "rez7", "consommable", "resurrect", 0.7),
        rez8 : new Item("Plume d'ange", "rez8", "consommable", "resurrect", 0.8),
        rez9 : new Item("Plume d'ange", "rez9", "consommable", "resurrect", 0.9),
        rez10 : new Item("Plume d'ange", "rez10", "consommable", "resurrect", 10),
    
        grenade: new Item("Grenade", "grenade", "consommable", "dégâts", 25)
    };
    
    constructor(nom, id, type, effet, valeur) {
        this.nom = nom;
        this.id = id;
        this.type = type;
        this.effet = effet;
        this.valeur = valeur;
    }

    static getItem(id) {
        return this.catalog[id]
    }
};